[package]
name = "tensorflow-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
futures = "0.3"
askama = "0.12.1"
actix-multipart = "0.6.1"
dotenv = "0.15"
